In [5]:
import pandas as pd
from datetime import datetime as dt

In [2]:
start_date = dt(2020, 11, 8)
end_date = dt(2020, 11, 9)

In [3]:
pd.date_range(start_date, end_date, freq='15T').to_pydatetime()[1].strftime("%Y%m%d%H%M%S")

'20201108001500'

In [4]:
"abc.zip".replace('.zip', '')

'abc'

In [27]:
cols = ['GlobalEventID','Day','MonthYear','Year','FractionDate','Actor1Code','Actor1Name','Actor1CountryCode','Actor1KnownGroupCode','Actor1EthnicCode','Actor1Religion1Code','Actor1Religion2Code','Actor1Type1Code','Actor1Type2Code','Actor1Type3Code','Actor2Code','Actor2Name','Actor2CountryCode','Actor2KnownGroupCode','Actor2EthnicCode','Actor2Religion1Code','Actor2Religion2Code','Actor2Type1Code','Actor2Type2Code','Actor2Type3Code','IsRootEvent','EventCode','EventBaseCode','EventRootCode','QuadClass','GoldsteinScale','NumMentions','NumSources','NumArticles','AvgTone','Actor1Geo_Type','Actor1Geo_FullName','Actor1Geo_CountryCode','Actor1Geo_ADM1Code','Actor1Geo_ADM2Code','Actor1Geo_Lat','Actor1Geo_Long','Actor1Geo_FeatureID','Actor2Geo_Type','Actor2Geo_FullName','Actor2Geo_CountryCode','Actor2Geo_ADM1Code','Actor2Geo_ADM2Code','Actor2Geo_Lat','Actor2Geo_Long','Actor2Geo_FeatureID','ActionGeo_Type','ActionGeo_FullName','ActionGeo_CountryCode','ActionGeo_ADM1Code','ActionGeo_ADM2Code','ActionGeo_Lat','ActionGeo_Long','ActionGeo_FeatureID','DATEADDED','SOURCEURL']

events = pd.read_csv("../../data/raw/20230101000000.translation.export.csv", delimiter="\t", header=None, names=cols)
events.head()

,GlobalEventID,Day,MonthYear,Year,FractionDate,Actor1Code,Actor1Name,Actor1CountryCode,Actor1KnownGroupCode,Actor1EthnicCode,...,ActionGeo_Type,ActionGeo_FullName,ActionGeo_CountryCode,ActionGeo_ADM1Code,ActionGeo_ADM2Code,ActionGeo_Lat,ActionGeo_Long,ActionGeo_FeatureID,DATEADDED,SOURCEURL
0,1078327865,20220101,202201,2022,2022.0027,MIL,MILITARY,NaN,NaN,NaN,...,1,Russia,RS,RS,NaN,60.0000,100.0000,RS,20230101000000,https://tass.ru/mezhdunarodnaya-panorama/16729839
1,1078327866,20220101,202201,2022,2022.0027,PRK,NORTH KOREA,PRK,NaN,NaN,...,4,"Pyongyang, P'yongyang-si, North Korea",KN,KN12,39681,39.0194,125.7550,-183459,20230101000000,https://www.fnnews.com/news/202301010518250550
2,1078327867,20220101,202201,2022,2022.0027,RUS,RUSSIAN,RUS,NaN,NaN,...,4,"Kiev, Ukraine (general), Ukraine",UP,UP00,28554,50.4333,30.5167,-1044367,20230101000000,https://www.novinky.cz/clanek/valka-na-ukrajin...
3,1078327868,20230101,202301,2023,2023.0027,NaN,NaN,NaN,NaN,NaN,...,1,Argentina,AR,AR,NaN,-34.0000,-64.0000,AR,20230101000000,https://www.pagina12.com.ar/512400-alberto-fer...
4,1078327869,20230101,202301,2023,2023.0027,NaN,NaN,NaN,NaN,NaN,...,1,Argentina,AR,AR,NaN,-34.0000,-64.0000,AR,20230101000000,https://www.pagina12.com.ar/512400-alberto-fer...

In [26]:
cols.index("ActionGeo_Lat")

56

In [10]:
header_mentions = ['GlobalEventID',
'EventTimeDate',
'MentionTimeDate',
'MentionType',
'MentionSourceName',
'MentionIdentifier',
'SentenceID',
'Actor1CharOffset',
'Actor2CharOffset',
'ActionCharOffset',
'InRawText',
'Confidence',
'MentionDocLen',
'MentionDocTone',
'MentionDocTranslationInfo',
'Extras']

In [15]:
mentions = pd.read_csv("../../data/raw/20230101000000.mentions.csv", delimiter="\t", header=None, names=header_mentions)
mentions

,GlobalEventID,EventTimeDate,MentionTimeDate,MentionType,MentionSourceName,MentionIdentifier,SentenceID,Actor1CharOffset,Actor2CharOffset,ActionCharOffset,InRawText,Confidence,MentionDocLen,MentionDocTone,MentionDocTranslationInfo,Extras
0,1078325979,20230101000000,20230101000000,1,pakobserver.net,https://pakobserver.net/google-launches-specia...,5,744,-1,756,1,100,875,8.227848,NaN,NaN
1,1078325980,20230101000000,20230101000000,1,pakobserver.net,https://pakobserver.net/google-launches-specia...,5,744,-1,850,1,100,875,8.227848,NaN,NaN
2,1078325981,20230101000000,20230101000000,1,theday.com,https://www.theday.com/local-news/20221231/wat...,2,73,154,96,1,50,6468,2.798507,NaN,NaN
3,1021482846,20220101184500,20230101000000,1,brazilsun.com,https://www.brazilsun.com/news/273296117/brazi...,8,2179,-1,2202,1,100,2178,-7.449857,NaN,NaN
4,1078325982,20230101000000,20230101000000,1,brazilsun.com,https://www.brazilsun.com/news/273296117/brazi...,8,2179,-1,2225,1,100,2178,-7.449857,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1428,1078327015,20230101000000,20230101000000,1,kgw.com,https://www.kgw.com/article/news/nation-world/...,12,1896,-1,1910,1,30,4299,-5.233380,NaN,NaN
1429,1078327016,20230101000000,20230101000000,1,fox43.com,https://www.fox43.com/article/news/nation-worl...,12,1896,1906,1927,0,20,4299,-5.233380,NaN,NaN
1430,1078327016,20230101000000,20230101000000,1,kgw.com,https://www.kgw.com/article/news/nation-world/...,12,1896,1906,1927,0,20,4299,-5.233380,NaN,NaN
1431,1078327017,20230101000000,20230101000000,1,fox43.com,https://www.fox43.com/article/news/nation-worl...,12,1896,1906,1938,0,20,4299,-5.233380,NaN,NaN
1432,1078327017,20230101000000,20230101000000,1,kgw.com,https://www.kgw.com/article/news/nation-world/...,12,1896,1906,1938,0,20,4299,-5.233380,NaN,NaN

In [17]:
len(mentions["MentionIdentifier"].unique())

197

In [13]:
def check_language(start, end):
    for date in pd.date_range(start, end, freq='15T').to_pydatetime():
        str_date = date.strftime("%Y%m%d%H%M%S")
        mentions = pd.read_csv(f"../../data/raw/{str_date}.mentions.csv", delimiter="\t", header=None, names=header_mentions, usecols=['MentionDocTranslationInfo']).squeeze()
        not_na_count = mentions.notna().sum()
        # print(not_na_count)
        if not_na_count > 0:
            print(f"Pas d'anglais Ã  cette date: {date}")

In [14]:
start = dt(2023, 1, 7)
end = dt(2023, 1, 8)
check_language(start, end)

In [21]:
gkg = pd.read_csv("../../data/raw/20230107003000.translation.gkg.csv", delimiter="\t", header=None, encoding = "ISO-8859-1", usecols=[25])
gkg

                                                    25
0    srclc:fra;eng:Moses 2.1.1 / MosesCore Europarl...
1    srclc:fra;eng:Moses 2.1.1 / MosesCore Europarl...
2    srclc:fra;eng:Moses 2.1.1 / MosesCore Europarl...
3    srclc:fra;eng:Moses 2.1.1 / MosesCore Europarl...
4    srclc:fra;eng:Moses 2.1.1 / MosesCore Europarl...
..                                                 ...
960                           srclc:vie;eng:GT-VIE 1.0
961                           srclc:vie;eng:GT-VIE 1.0
962                           srclc:vie;eng:GT-VIE 1.0
963                           srclc:vie;eng:GT-VIE 1.0
964                           srclc:slv;eng:GT-SLV 1.0

[965 rows x 1 columns]

In [2]:
gkg_headers= ['GKGRecordID', 'DATE', 'SourceCollectionIdentifier', 'SourceCommonName', 'DocumentIdentifier',
                   'Counts', 'V2Counts', 'Themes', 'V2Themes', 'Locations', 'V2Locations', 'Persons', 'V2Persons',
                   'Organizations', 'V2Organizations', 'V2Tone', 'Dates', 'GCAM', 'SharingImage', 'RelatedImages',
                   'SocialImageEmbeds', 'SocialVideoEmbeds', 'Quotations', 'AllNames', 'Amounts', 'TranslationInfo','Extras']

In [20]:
gkg_headers.index("V2Tone")

15

In [13]:
gkg_translate = pd.read_csv("../../data/raw/20230101000000.translation.gkg.csv", delimiter="\t",
                                    header=None,
                                    on_bad_lines=None,
                                    encoding='ISO-8859-1',
                                    names=gkg_headers,
                                    usecols= ['GKGRecordID','DATE','SourceCollectionIdentifier','SourceCommonName','DocumentIdentifier','Counts','Themes','Organizations','V2Tone','Dates','TranslationInfo']
                                    )
gkg_translate

,GKGRecordID,DATE,SourceCollectionIdentifier,SourceCommonName,DocumentIdentifier,Counts,Themes,Organizations,V2Tone,Dates,TranslationInfo
0,20230101000000-T0,20230101000000,1,novinky.cz,https://www.novinky.cz/clanek/valka-na-ukrajin...,NaN,MANMADE_DISASTER_IMPLIED;ARMEDCONFLICT;URBAN;T...,reuters,"0.60790273556231,4.55927051671733,3.9513677811...",NaN,srclc:ces;eng:Moses 2.1.1 / MosesCore Europarl...
1,20230101000000-T1,20230101000000,1,mesec.cz,https://www.mesec.cz/rejstrik-firem/firma-clas...,NaN,TAX_FNCACT;TAX_FNCACT_BARBER;TAX_FNCACT_SELF_E...,NaN,"-2.08333333333333,0,2.08333333333333,2.0833333...",NaN,srclc:ces;eng:Moses 2.1.1 / MosesCore Europarl...
2,20230101000000-T2,20230101000000,1,mesec.cz,https://www.mesec.cz/rejstrik-firem/firma-petr...,NaN,TAX_FNCACT;TAX_FNCACT_SELF_EMPLOYED;WB_698_TRA...,NaN,"-2.12765957446809,0,2.12765957446809,2.1276595...",NaN,srclc:ces;eng:Moses 2.1.1 / MosesCore Europarl...
3,20230101000000-T3,20230101000000,1,mesec.cz,https://www.mesec.cz/rejstrik-firem/firma-jan-...,NaN,TAX_FNCACT;TAX_FNCACT_SELF_EMPLOYED;WB_698_TRA...,NaN,"-2.10526315789474,0,2.10526315789474,2.1052631...",NaN,srclc:ces;eng:Moses 2.1.1 / MosesCore Europarl...
4,20230101000000-T4,20230101000000,1,mesec.cz,https://www.mesec.cz/rejstrik-firem/firma-jan-...,NaN,TAX_FNCACT;TAX_FNCACT_SELF_EMPLOYED;WB_698_TRA...,NaN,"-2.1505376344086,0,2.1505376344086,2.150537634...",NaN,srclc:ces;eng:Moses 2.1.1 / MosesCore Europarl...
...,...,...,...,...,...,...,...,...,...,...,...
760,20230101000000-T760,20230101000000,1,baomoi.com,https://baomoi.com/doanh-nghiep-phai-kiem-ke-k...,NaN,WB_678_DIGITAL_GOVERNMENT;WB_694_BROADCAST_AND...,conjugate international;center development;cen...,"-0.597609561752988,2.39043824701195,2.98804780...",NaN,srclc:vie;eng:GT-VIE 1.0
761,20230101000000-T761,20230101000000,1,baomoi.com,https://baomoi.com/tho-dung-chay-so-tim-tet/c/...,AFFECT#3#health weak#0######;,TAX_FNCACT;TAX_FNCACT_ARTISAN;TAX_FNCACT_PORTE...,NaN,"2.14752567693744,5.22875816993464,3.0812324929...",NaN,srclc:vie;eng:GT-VIE 1.0
762,20230101000000-T762,20230101000000,1,baomoi.com,https://baomoi.com/nu-giao-su-nguoi-viet-thanh...,NaN,EDUCATION;,field research;fund science national fine;i so...,"3.16815597075548,4.9553208773355,1.78716490658...",NaN,srclc:vie;eng:GT-VIE 1.0
763,20230101000000-T763,20230101000000,1,baomoi.com,https://baomoi.com/khoi-cong-12-goi-thau-thuoc...,NaN,TAX_FNCACT;TAX_FNCACT_CONTRACTOR;TAX_WORLDMAMM...,NaN,"-1.40845070422535,0,1.40845070422535,1.4084507...",NaN,srclc:vie;eng:GT-VIE 1.0
764,20230101000000-T764,20230101000000,1,avto.info,https://www.avto.info/arhiv/Novosti/Januar_2023/,NaN,LEGISLATION;EPU_POLICY;EPU_POLICY_LAW;TAX_FNCA...,NaN,"1.0752688172043,1.0752688172043,0,1.0752688172...",NaN,srclc:slv;eng:GT-SLV 1.0

In [14]:
gkg = pd.read_csv("../../data/raw/20230101000000.gkg.csv", delimiter="\t",
                                    header=None,
                                    on_bad_lines=None,
                                    encoding='ISO-8859-1',
                                    names=gkg_headers,
                                    usecols= ['GKGRecordID','DATE','SourceCollectionIdentifier','SourceCommonName','DocumentIdentifier','Counts','Themes','Organizations','V2Tone','Dates','TranslationInfo']
                                    )
gkg

,GKGRecordID,DATE,SourceCollectionIdentifier,SourceCommonName,DocumentIdentifier,Counts,Themes,Organizations,V2Tone,Dates,TranslationInfo
0,20230101000000-0,20230101000000,1,msn.com,http://www.msn.com/en-nz/news/other/celebritie...,NaN,TAX_FNCACT;TAX_FNCACT_ACTRESS;TAX_WORLDLANGUAG...,NaN,"-3.92156862745098,7.84313725490196,11.76470588...",NaN,NaN
1,20230101000000-1,20230101000000,1,voazimbabwe.com,https://www.voazimbabwe.com/a/6899258.html,NaN,TAX_FNCACT;TAX_FNCACT_POPE;TAX_RELIGION;TAX_RE...,college of cardinals;roman catholic church;cat...,"-3.02171860245515,1.98300283286119,5.004721435...",1#0#0#2013#81;3#2#11#2013#839;1#0#0#1983#1711,NaN
2,20230101000000-2,20230101000000,1,johnogroat-journal.co.uk,https://www.johnogroat-journal.co.uk/news/nati...,KILL#3#ultramale worlds#1#Italy#IT#IT#42.83333...,TAX_FNCACT;TAX_FNCACT_ARTIST;TAX_FNCACT_KNIGHT...,instagram;grayson art club;claire;royal scotti...,"4.54545454545455,5.89225589225589,1.3468013468...",1#0#0#2014#1783;4#7#22#0#3287,NaN
3,20230101000000-3,20230101000000,1,chinanationalnews.com,https://www.chinanationalnews.com/news/2732952...,NaN,LEADER;TAX_FNCACT;TAX_FNCACT_PRESIDENT;USPEC_P...,colombo stock exchange;xinhua;china communicat...,"-1.06761565836299,1.42348754448399,2.491103202...",4#12#23#0#702,NaN
4,20230101000000-4,20230101000000,1,annistonstar.com,https://www.annistonstar.com/the_daily_home/fr...,NaN,TAX_FNCACT;TAX_FNCACT_PASTOR;TAX_WORLDMAMMALS;...,judson college;ministers foundation,"-1.07991360691145,3.67170626349892,4.751619870...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
490,20230101000000-490,20230101000000,1,watoday.com.au,https://www.watoday.com.au/world/europe/missil...,WOUND#20##1#Japan#JA#JA#36#138#JA;CRISISLEX_CR...,CRISISLEX_CRISISLEXREC;ARMEDCONFLICT;TAX_ETHNI...,national advanced missile systems;washington p...,"-4.76190476190476,2.04081632653061,6.802721088...",NaN,NaN
491,20230101000000-491,20230101000000,1,postregister.com,https://www.postregister.com/news/national/new...,NaN,TAX_FNCACT;TAX_FNCACT_INVESTOR;MARITIME_INCIDE...,america statehouse news initiative,"1.86625194401244,3.26594090202177,1.3996889580...",NaN,NaN
492,20230101000000-492,20230101000000,1,nbcwashington.com,https://www.nbcwashington.com/news/national-in...,"ARREST#4##2#Idaho, United States#US#USID#44.23...",ARREST;SOC_GENERALCRIME;CRISISLEX_C07_SAFETY;E...,washington state university;pennsylvania state...,"-2.81973816717019,2.21550855991944,5.035246727...",NaN,NaN
493,20230101000000-493,20230101000000,1,thestar.com.my,https://www.thestar.com.my/news/nation/2023/01...,NaN,ELECTION;TAX_FNCACT;TAX_FNCACT_MINISTER;LEADER...,badminton association of malaysia;national no;...,"-3.07971014492754,2.35507246376812,5.434782608...",4#1#26#0#998;4#1#30#0#1055;4#2#11#0#1168;4#4#1...,NaN
494,20230101000000-494,20230101000000,1,nichegamer.com,https://nichegamer.com/sam-max-the-devils-play...,NaN,NaN,NaN,"-2.77777777777778,0,2.77777777777778,2.7777777...",1#0#0#2010#310,NaN

In [19]:
len(gkg["V2Tone"].unique())

427

a) afficher le nombre dâ€™articles/Ã©vÃ¨nements quâ€™il y a eu pour chaque triplet (jour, pays de lâ€™Ã©vÃ¨nement, langue de lâ€™article).

jour : Events[ Day, YearMonth, Year, DateAdd ] \
pays : Events[ (GeoEvents) ] (the Geo_FeatureID column should be used) \
langue : Mentions[ MentionDocTranslationInfo ]

lien event -> mention: GlobalEventID \
lien mention -> gkg: mentionIdentifier -> DocumentIdentifier

Localisation:
- Origine de l'actor
- Lieu de l'actor au moment de l'Ã©venement
- Lieu de dÃ©roulement de l'action

Un acteur a donc un lieu d'origine fixe mais aussi un lieu associÃ© Ã  chaque Ã©venement le concernant. Comment materialiser cela dans le graphe ? 
1) Noeud Lieu pour les origines des actors et les Ã©venements + caractÃ©risation du lieu dans le lien acteur Ã©venement\
La redondance d'un noeud gÃ©ographique et de propriÃ©tÃ© gÃ©ographique dans des liens n'est elle pas dÃ©gueulasse ?
2) Pas de noeud lieu -> caractÃ©ristiques transferer dans les noeuds d'origines (origine devient une propriÃ©tÃ© d'actor ou event)

D'aprÃ¨s les questions, il est prÃ©ferable de garder un noeud lieu, la localisation des actors n'est pas trÃ¨s utiles pour y rÃ©pondre

### Person

Besoin de differencier les acteurs Ã  un niveau plus fin -> q3 (filtrer les personnes qui ...) \
Comment reprÃ©senter Ã§a dans Neo4j ? Heritage possible ? -> un noeud actor, comportant les propriÃ©tÃ© principales, associÃ© Ã  un noeud person ou organization etc