In [1]:
import pandas as pd
from datetime import datetime as dt

In [2]:
start_date = dt(2020, 11, 8)
end_date = dt(2020, 11, 9)

In [3]:
pd.date_range(start_date, end_date, freq='15T').to_pydatetime()[1].strftime("%Y%m%d%H%M%S")

'20201108001500'

In [4]:
"abc.zip".replace('.zip', '')

'abc'

In [13]:
events = pd.read_csv("../../data/raw/20230101000000.translation.export.csv", delimiter="\t", header=None)
print(events.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 332 entries, 0 to 331
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       332 non-null    int64
 1   1       332 non-null    int64
 2   2       332 non-null    int64
 3   3       332 non-null    int64
 4   4       332 non-null    float64
 5   5       280 non-null    object
 6   6       280 non-null    object
 7   7       174 non-null    object
 8   8       4 non-null      object
 9   9       0 non-null      float64
 10  10      3 non-null      object
 11  11      2 non-null      object
 12  12      139 non-null    object
 13  13      4 non-null      object
 14  14      0 non-null      float64
 15  15      198 non-null    object
 16  16      198 non-null    object
 17  17      116 non-null    object
 18  18      3 non-null      object
 19  19      0 non-null      float64
 20  20      1 non-null      object
 21  21      1 non-null      object
 22  22      84 non-null     object
 23  23      2 non-null      object
 24  24      0 non-null      float64
 25  25      332 non-null    int64
 26  26      332 non-null    int64
 27  27      332 non-null    int64
 28  28      332 non-null    int64
 29  29      332 non-null    int64
 30  30      332 non-null    float64
 31  31      332 non-null    int64
 32  32      332 non-null    int64
 33  33      332 non-null    int64
 34  34      332 non-null    float64
 35  35      332 non-null    int64
 36  36      264 non-null    object
 37  37      264 non-null    object
 38  38      264 non-null    object
 39  39      140 non-null    object
 40  40      264 non-null    float64
 41  41      264 non-null    float64
 42  42      264 non-null    object
 43  43      332 non-null    int64
 44  44      189 non-null    object
 45  45      189 non-null    object
 46  46      189 non-null    object
 47  47      96 non-null     object
 48  48      189 non-null    float64
 49  49      189 non-null    float64
 50  50      189 non-null    object
 51  51      332 non-null    int64
 52  52      311 non-null    object
 53  53      311 non-null    object
 54  54      311 non-null    object
 55  55      166 non-null    object
 56  56      311 non-null    float64
 57  57      311 non-null    float64
 58  58      311 non-null    object
 59  59      332 non-null    int64
 60  60      332 non-null    object
dtypes: float64(13), int64(16), object(32)
memory usage: 158.3+ KB
None

In [14]:
cols = ['GlobalEventID','Day','MonthYear','Year','FractionDate','Actor1Code','Actor1Name','Actor1CountryCode','Actor1KnownGroupCode','Actor1EthnicCode','Actor1Religion1Code','Actor1Religion2Code','Actor1Type1Code','Actor1Type2Code','Actor1Type3Code','Actor2Code','Actor2Name','Actor2CountryCode','Actor2KnownGroupCode','Actor2EthnicCode','Actor2Religion1Code','Actor2Religion2Code','Actor2Type1Code','Actor2Type2Code','Actor2Type3Code','IsRootEvent','EventCode','EventBaseCode','EventRootCode','QuadClass','GoldsteinScale','NumMentions','NumSources','NumArticles','AvgTone','Actor1Geo_Type','Actor1Geo_FullName','Actor1Geo_CountryCode','Actor1Geo_ADM1Code','Actor1Geo_ADM2Code','Actor1Geo_Lat','Actor1Geo_Long','Actor1Geo_FeatureID','Actor2Geo_Type','Actor2Geo_FullName','Actor2Geo_CountryCode','Actor2Geo_ADM1Code','Actor2Geo_ADM2Code','Actor2Geo_Lat','Actor2Geo_Long','Actor2Geo_FeatureID','ActionGeo_Type','ActionGeo_FullName','ActionGeo_CountryCode','ActionGeo_ADM1Code','ActionGeo_ADM2Code','ActionGeo_Lat','ActionGeo_Long','ActionGeo_FeatureID','DATEADDED','SOURCEURL']

events.columns = cols
events

,GlobalEventID,Day,MonthYear,Year,FractionDate,Actor1Code,Actor1Name,Actor1CountryCode,Actor1KnownGroupCode,Actor1EthnicCode,...,ActionGeo_Type,ActionGeo_FullName,ActionGeo_CountryCode,ActionGeo_ADM1Code,ActionGeo_ADM2Code,ActionGeo_Lat,ActionGeo_Long,ActionGeo_FeatureID,DATEADDED,SOURCEURL
0,1078327865,20220101,202201,2022,2022.0027,MIL,MILITARY,NaN,NaN,NaN,...,1,Russia,RS,RS,NaN,60.0000,100.0000,RS,20230101000000,https://tass.ru/mezhdunarodnaya-panorama/16729839
1,1078327866,20220101,202201,2022,2022.0027,PRK,NORTH KOREA,PRK,NaN,NaN,...,4,"Pyongyang, P'yongyang-si, North Korea",KN,KN12,39681,39.0194,125.7550,-183459,20230101000000,https://www.fnnews.com/news/202301010518250550
2,1078327867,20220101,202201,2022,2022.0027,RUS,RUSSIAN,RUS,NaN,NaN,...,4,"Kiev, Ukraine (general), Ukraine",UP,UP00,28554,50.4333,30.5167,-1044367,20230101000000,https://www.novinky.cz/clanek/valka-na-ukrajin...
3,1078327868,20230101,202301,2023,2023.0027,NaN,NaN,NaN,NaN,NaN,...,1,Argentina,AR,AR,NaN,-34.0000,-64.0000,AR,20230101000000,https://www.pagina12.com.ar/512400-alberto-fer...
4,1078327869,20230101,202301,2023,2023.0027,NaN,NaN,NaN,NaN,NaN,...,1,Argentina,AR,AR,NaN,-34.0000,-64.0000,AR,20230101000000,https://www.pagina12.com.ar/512400-alberto-fer...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,1078328192,20230101,202301,2023,2023.0027,VAT,VATICAN,VAT,NaN,NaN,...,4,"Munich, Bayern, Germany",GM,GM02,16532,48.1500,11.5833,-1829149,20230101000000,https://wtop.com/news/2022/12/el-rottweiler-de...
328,1078328193,20230101,202301,2023,2023.0027,VAT,VATICAN,VAT,NaN,NaN,...,1,Iraq,IZ,IZ,NaN,33.0000,44.0000,IZ,20230101000000,https://wtop.com/news/2022/12/el-rottweiler-de...
329,1078328194,20230101,202301,2023,2023.0027,VAT,VATICAN,VAT,NaN,NaN,...,2,"New York, United States",US,USNY,NaN,42.1497,-74.9384,NY,20230101000000,https://wtop.com/news/2022/12/el-rottweiler-de...
330,1078328195,20230101,202301,2023,2023.0027,VEN,VENEZUELA,VEN,NaN,NaN,...,4,"Brasilia, Distrito Federal, Brazil",BR,BR07,40202,-15.7833,-47.9167,-631243,20230101000000,https://www.bahianoticias.com.br:443/folha/not...
331,1078328196,20230101,202301,2023,2023.0027,VEN,VENEZUELA,VEN,NaN,NaN,...,1,Venezuela,VE,VE,NaN,8.0000,-66.0000,VE,20230101000000,https://www.bahianoticias.com.br:443/folha/not...

In [9]:
cols.index("Actor2Name")
MATCH (event:Event {GlobalEventID : "1078327865"})
MATCH (ressource:Ressource {OriginalID : "OriginalID: https://tass.ru/mezhdunarodnaya-panorama/16729839"})
MERGE (ressource)-[:MENTIONS]->(event)
RETURN event, ressource

16

In [11]:
mentions = pd.read_csv("../../data/raw/20230101000000.translation.mentions.csv", delimiter="\t", header=None)
mentions

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,1078327865,20230101000000,20230101000000,1,tass.ru,https://tass.ru/mezhdunarodnaya-panorama/16729839,9,2966,-1,3002,1,100,4492,0.953678,srclc:rus;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
1,1078327865,20230101000000,20230101000000,1,tass.ru,https://tass.ru/armiya-i-opk/16729333,3,348,-1,384,1,100,1477,2.857143,srclc:rus;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
2,1078327866,20230101000000,20230101000000,1,etoday.co.kr,https://www.etoday.co.kr/news/view/2208178,5,1610,-1,1708,1,100,2618,0.000000,srclc:kor;eng:GT-KOR 1.0,NaN
3,1078327866,20230101000000,20230101000000,1,fnnews.com,https://www.fnnews.com/news/202301010518250550,7,2807,-1,2900,1,100,3062,-3.036876,srclc:kor;eng:GT-KOR 1.0,NaN
4,1078327867,20230101000000,20230101000000,1,novinky.cz,https://www.novinky.cz/clanek/valka-na-ukrajin...,5,639,625,611,1,100,1964,0.613497,srclc:ces;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,1078328192,20230101000000,20230101000000,1,wtop.com,https://wtop.com/news/2022/12/el-rottweiler-de...,20,8389,8407,8419,0,20,13874,-3.765511,srclc:spa;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
362,1078328193,20230101000000,20230101000000,1,wtop.com,https://wtop.com/news/2022/12/el-rottweiler-de...,20,8389,8407,8419,1,80,13874,-3.765511,srclc:spa;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
363,1078328194,20230101000000,20230101000000,1,wtop.com,https://wtop.com/news/2022/12/el-rottweiler-de...,10,4111,4129,4119,0,40,13874,-3.765511,srclc:spa;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
364,1078328195,20230101000000,20230101000000,1,bahianoticias.com.br,https://www.bahianoticias.com.br:443/folha/not...,10,3285,3392,3343,1,80,4252,0.928793,srclc:por;eng:GT-POR 1.0,NaN
365,1078328196,20230101000000,20230101000000,1,bahianoticias.com.br,https://www.bahianoticias.com.br:443/folha/not...,10,3285,3392,3343,0,20,4252,0.928793,srclc:por;eng:GT-POR 1.0,NaN

In [12]:
header_mentions = ['GlobalEventID',
'EventTimeDate',
'MentionTimeDate',
'MentionType',
'MentionSourceName',
'MentionIdentifier',
'SentenceID',
'Actor1CharOffset',
'Actor2CharOffset',
'ActionCharOffset',
'InRawText',
'Confidence',
'MentionDocLen',
'MentionDocTone',
'MentionDocTranslationInfo',
'Extras']

mentions.columns = header_mentions
mentions

,GlobalEventID,EventTimeDate,MentionTimeDate,MentionType,MentionSourceName,MentionIdentifier,SentenceID,Actor1CharOffset,Actor2CharOffset,ActionCharOffset,InRawText,Confidence,MentionDocLen,MentionDocTone,MentionDocTranslationInfo,Extras
0,1078327865,20230101000000,20230101000000,1,tass.ru,https://tass.ru/mezhdunarodnaya-panorama/16729839,9,2966,-1,3002,1,100,4492,0.953678,srclc:rus;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
1,1078327865,20230101000000,20230101000000,1,tass.ru,https://tass.ru/armiya-i-opk/16729333,3,348,-1,384,1,100,1477,2.857143,srclc:rus;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
2,1078327866,20230101000000,20230101000000,1,etoday.co.kr,https://www.etoday.co.kr/news/view/2208178,5,1610,-1,1708,1,100,2618,0.000000,srclc:kor;eng:GT-KOR 1.0,NaN
3,1078327866,20230101000000,20230101000000,1,fnnews.com,https://www.fnnews.com/news/202301010518250550,7,2807,-1,2900,1,100,3062,-3.036876,srclc:kor;eng:GT-KOR 1.0,NaN
4,1078327867,20230101000000,20230101000000,1,novinky.cz,https://www.novinky.cz/clanek/valka-na-ukrajin...,5,639,625,611,1,100,1964,0.613497,srclc:ces;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,1078328192,20230101000000,20230101000000,1,wtop.com,https://wtop.com/news/2022/12/el-rottweiler-de...,20,8389,8407,8419,0,20,13874,-3.765511,srclc:spa;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
362,1078328193,20230101000000,20230101000000,1,wtop.com,https://wtop.com/news/2022/12/el-rottweiler-de...,20,8389,8407,8419,1,80,13874,-3.765511,srclc:spa;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
363,1078328194,20230101000000,20230101000000,1,wtop.com,https://wtop.com/news/2022/12/el-rottweiler-de...,10,4111,4129,4119,0,40,13874,-3.765511,srclc:spa;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
364,1078328195,20230101000000,20230101000000,1,bahianoticias.com.br,https://www.bahianoticias.com.br:443/folha/not...,10,3285,3392,3343,1,80,4252,0.928793,srclc:por;eng:GT-POR 1.0,NaN
365,1078328196,20230101000000,20230101000000,1,bahianoticias.com.br,https://www.bahianoticias.com.br:443/folha/not...,10,3285,3392,3343,0,20,4252,0.928793,srclc:por;eng:GT-POR 1.0,NaN

In [22]:
mentions = pd.read_csv("../../data/raw/20220707000000.mentions.csv", delimiter="\t", header=None, names=header_mentions, usecols=['ActionGeo_CountryCode']).squeeze()
mentions

ValueError: Usecols do not match columns, columns expected but not found: ['ActionGeo_CountryCode']

In [13]:
def check_language(start, end):
    for date in pd.date_range(start, end, freq='15T').to_pydatetime():
        str_date = date.strftime("%Y%m%d%H%M%S")
        mentions = pd.read_csv(f"../../data/raw/{str_date}.mentions.csv", delimiter="\t", header=None, names=header_mentions, usecols=['MentionDocTranslationInfo']).squeeze()
        not_na_count = mentions.notna().sum()
        # print(not_na_count)
        if not_na_count > 0:
            print(f"Pas d'anglais à cette date: {date}")

In [14]:
start = dt(2023, 1, 7)
end = dt(2023, 1, 8)
check_language(start, end)

In [21]:
gkg = pd.read_csv("../../data/raw/20230107003000.translation.gkg.csv", delimiter="\t", header=None, encoding = "ISO-8859-1", usecols=[25])
gkg

                                                    25
0    srclc:fra;eng:Moses 2.1.1 / MosesCore Europarl...
1    srclc:fra;eng:Moses 2.1.1 / MosesCore Europarl...
2    srclc:fra;eng:Moses 2.1.1 / MosesCore Europarl...
3    srclc:fra;eng:Moses 2.1.1 / MosesCore Europarl...
4    srclc:fra;eng:Moses 2.1.1 / MosesCore Europarl...
..                                                 ...
960                           srclc:vie;eng:GT-VIE 1.0
961                           srclc:vie;eng:GT-VIE 1.0
962                           srclc:vie;eng:GT-VIE 1.0
963                           srclc:vie;eng:GT-VIE 1.0
964                           srclc:slv;eng:GT-SLV 1.0

[965 rows x 1 columns]

a) afficher le nombre d’articles/évènements qu’il y a eu pour chaque triplet (jour, pays de l’évènement, langue de l’article).

jour : Events[ Day, YearMonth, Year, DateAdd ] \
pays : Events[ (GeoEvents) ] (the Geo_FeatureID column should be used) \
langue : Mentions[ MentionDocTranslationInfo ]

lien event -> mention: GlobalEventID \
lien mention -> gkg: mentionIdentifier -> DocumentIdentifier

Localisation:
- Origine de l'actor
- Lieu de l'actor au moment de l'évenement
- Lieu de déroulement de l'action

Un acteur a donc un lieu d'origine fixe mais aussi un lieu associé à chaque évenement le concernant. Comment materialiser cela dans le graphe ? 
1) Noeud Lieu pour les origines des actors et les évenements + caractérisation du lieu dans le lien acteur évenement\
La redondance d'un noeud géographique et de propriété géographique dans des liens n'est elle pas dégueulasse ?
2) Pas de noeud lieu -> caractéristiques transferer dans les noeuds d'origines (origine devient une propriété d'actor ou event)

D'après les questions, il est préferable de garder un noeud lieu, la localisation des actors n'est pas très utiles pour y répondre

### Person

Besoin de differencier les acteurs à un niveau plus fin -> q3 (filtrer les personnes qui ...) \
Comment représenter ça dans Neo4j ? Heritage possible ? -> un noeud actor, comportant les propriété principales, associé à un noeud person ou organization etc