In [1]:
import pandas as pd
from datetime import datetime as dt

In [6]:
start_date = dt(2020, 11, 8)
end_date = dt(2020, 11, 9)

In [10]:
pd.date_range(start_date, end_date, freq='15T').to_pydatetime()[1].strftime("%Y%m%d%H%M%S")

'20201108001500'

In [13]:
"abc.zip".replace('.zip', '')

'abc'

In [2]:
events = pd.read_csv("../../data/raw/20220707000000.export.csv", delimiter="\t", header=None)
print(events.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2612 entries, 0 to 2611
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2612 non-null   int64
 1   1       2612 non-null   int64
 2   2       2612 non-null   int64
 3   3       2612 non-null   int64
 4   4       2612 non-null   float64
 5   5       2324 non-null   object
 6   6       2324 non-null   object
 7   7       1403 non-null   object
 8   8       29 non-null     object
 9   9       18 non-null     object
 10  10      53 non-null     object
 11  11      16 non-null     object
 12  12      1079 non-null   object
 13  13      51 non-null     object
 14  14      0 non-null      float64
 15  15      1734 non-null   object
 16  16      1734 non-null   object
 17  17      1023 non-null   object
 18  18      30 non-null     object
 19  19      14 non-null     object
 20  20      25 non-null     object
 21  21      7 non-null      object
 22  22      880 non-null    object
 23  23      43 non-null     object
 24  24      0 non-null      float64
 25  25      2612 non-null   int64
 26  26      2612 non-null   int64
 27  27      2612 non-null   int64
 28  28      2612 non-null   int64
 29  29      2612 non-null   int64
 30  30      2612 non-null   float64
 31  31      2612 non-null   int64
 32  32      2612 non-null   int64
 33  33      2612 non-null   int64
 34  34      2612 non-null   float64
 35  35      2612 non-null   int64
 36  36      2217 non-null   object
 37  37      2217 non-null   object
 38  38      2217 non-null   object
 39  39      1365 non-null   object
 40  40      2217 non-null   float64
 41  41      2217 non-null   float64
 42  42      2217 non-null   object
 43  43      2612 non-null   int64
 44  44      1668 non-null   object
 45  45      1668 non-null   object
 46  46      1668 non-null   object
 47  47      827 non-null    object
 48  48      1668 non-null   float64
 49  49      1668 non-null   float64
 50  50      1668 non-null   object
 51  51      2612 non-null   int64
 52  52      2477 non-null   object
 53  53      2477 non-null   object
 54  54      2477 non-null   object
 55  55      1182 non-null   object
 56  56      2477 non-null   float64
 57  57      2477 non-null   float64
 58  58      2477 non-null   object
 59  59      2612 non-null   int64
 60  60      2612 non-null   object
dtypes: float64(11), int64(16), object(34)
memory usage: 1.2+ MB
None

In [3]:
cols = ['GlobalEventID','Day','MonthYear','Year','FractionDate','Actor1Code','Actor1Name','Actor1CountryCode','Actor1KnownGroupCode','Actor1EthnicCode','Actor1Religion1Code','Actor1Religion2Code','Actor1Type1Code','Actor1Type2Code','Actor1Type3Code','Actor2Code','Actor2Name','Actor2CountryCode','Actor2KnownGroupCode','Actor2EthnicCode','Actor2Religion1Code','Actor2Religion2Code','Actor2Type1Code','Actor2Type2Code','Actor2Type3Code','IsRootEvent','EventCode','EventBaseCode','EventRootCode','QuadClass','GoldsteinScale','NumMentions','NumSources','NumArticles','AvgTone','Actor1Geo_Type','Actor1Geo_FullName','Actor1Geo_CountryCode','Actor1Geo_ADM1Code','Actor1Geo_ADM2Code','Actor1Geo_Lat','Actor1Geo_Long','Actor1Geo_FeatureID','Actor2Geo_Type','Actor2Geo_FullName','Actor2Geo_CountryCode','Actor2Geo_ADM1Code','Actor2Geo_ADM2Code','Actor2Geo_Lat','Actor2Geo_Long','Actor2Geo_FeatureID','ActionGeo_Type','ActionGeo_FullName','ActionGeo_CountryCode','ActionGeo_ADM1Code','ActionGeo_ADM2Code','ActionGeo_Lat','ActionGeo_Long','ActionGeo_FeatureID','DATEADDED','SOURCEURL']

events.columns = cols
events

,GlobalEventID,Day,MonthYear,Year,FractionDate,Actor1Code,Actor1Name,Actor1CountryCode,Actor1KnownGroupCode,Actor1EthnicCode,...,ActionGeo_Type,ActionGeo_FullName,ActionGeo_CountryCode,ActionGeo_ADM1Code,ActionGeo_ADM2Code,ActionGeo_Lat,ActionGeo_Long,ActionGeo_FeatureID,DATEADDED,SOURCEURL
0,1052900674,20210707,202107,2021,2021.5123,JUD,SUPREME COURT,NaN,NaN,NaN,...,2,"Alabama, United States",US,USAL,NaN,32.7990,-86.8073,AL,20220707000000,https://www.wbal.com/article/573702/111/north-...
1,1052900675,20210707,202107,2021,2021.5123,JUD,SUPREME COURT,NaN,NaN,NaN,...,2,"South Carolina, United States",US,USSC,NaN,33.8191,-80.9066,SC,20220707000000,https://www.wbal.com/article/573702/111/north-...
2,1052900676,20210707,202107,2021,2021.5123,JUD,SUPREME COURT,NaN,NaN,NaN,...,2,"West Virginia, United States",US,USWV,NaN,38.4680,-80.9696,WV,20220707000000,https://www.jdsupra.com/legalnews/epa-s-clean-...
3,1052900677,20210707,202107,2021,2021.5123,USA,TEXAS,USA,NaN,NaN,...,3,"Raleigh, North Carolina, United States",US,USNC,NC183,35.7721,-78.6386,1024242,20220707000000,https://www.goshennews.com/news/national_news/...
4,1052900678,20210707,202107,2021,2021.5123,USA,TEXAS,USA,NaN,NaN,...,2,"New Jersey, United States",US,USNJ,NaN,40.3140,-74.5089,NJ,20220707000000,https://www.goshennews.com/news/national_news/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2607,1052903281,20220707,202207,2022,2022.5123,scoGOV,SCOTTISH,NaN,NaN,sco,...,1,United Kingdom,UK,UK,NaN,54.0000,-4.0000,UK,20220707000000,https://www.warringtonguardian.co.uk/news/2026...
2608,1052903282,20220707,202207,2022,2022.5123,scoGOV,SCOTTISH,NaN,NaN,sco,...,1,United Kingdom,UK,UK,NaN,54.0000,-4.0000,UK,20220707000000,https://www.warringtonguardian.co.uk/news/2026...
2609,1052903283,20220707,202207,2022,2022.5123,tam,TAMIL,NaN,NaN,tam,...,4,"Sagaing, Sagain, Myanmar",BM,BM10,41820,21.8667,95.9833,-440968,20220707000000,https://www.southeastasiapost.com/news/2726118...
2610,1052903284,20220707,202207,2022,2022.5123,tam,TAMIL,NaN,NaN,tam,...,1,India,IN,IN,NaN,20.0000,77.0000,IN,20220707000000,https://www.southeastasiapost.com/news/2726118...
2611,1052903285,20220707,202207,2022,2022.5123,tam,TAMIL,NaN,NaN,tam,...,1,India,IN,IN,NaN,20.0000,77.0000,IN,20220707000000,https://www.southeastasiapost.com/news/2726118...

In [9]:
cols.index("EventCode")

26

In [4]:
mentions = pd.read_csv("../../data/raw/20230101000000.mentions.csv", delimiter="\t", header=None)
mentions

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,1078325979,20230101000000,20230101000000,1,pakobserver.net,https://pakobserver.net/google-launches-specia...,5,744,-1,756,1,100,875,8.227848,NaN,NaN
1,1078325980,20230101000000,20230101000000,1,pakobserver.net,https://pakobserver.net/google-launches-specia...,5,744,-1,850,1,100,875,8.227848,NaN,NaN
2,1078325981,20230101000000,20230101000000,1,theday.com,https://www.theday.com/local-news/20221231/wat...,2,73,154,96,1,50,6468,2.798507,NaN,NaN
3,1021482846,20220101184500,20230101000000,1,brazilsun.com,https://www.brazilsun.com/news/273296117/brazi...,8,2179,-1,2202,1,100,2178,-7.449857,NaN,NaN
4,1078325982,20230101000000,20230101000000,1,brazilsun.com,https://www.brazilsun.com/news/273296117/brazi...,8,2179,-1,2225,1,100,2178,-7.449857,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1428,1078327015,20230101000000,20230101000000,1,kgw.com,https://www.kgw.com/article/news/nation-world/...,12,1896,-1,1910,1,30,4299,-5.233380,NaN,NaN
1429,1078327016,20230101000000,20230101000000,1,fox43.com,https://www.fox43.com/article/news/nation-worl...,12,1896,1906,1927,0,20,4299,-5.233380,NaN,NaN
1430,1078327016,20230101000000,20230101000000,1,kgw.com,https://www.kgw.com/article/news/nation-world/...,12,1896,1906,1927,0,20,4299,-5.233380,NaN,NaN
1431,1078327017,20230101000000,20230101000000,1,fox43.com,https://www.fox43.com/article/news/nation-worl...,12,1896,1906,1938,0,20,4299,-5.233380,NaN,NaN
1432,1078327017,20230101000000,20230101000000,1,kgw.com,https://www.kgw.com/article/news/nation-world/...,12,1896,1906,1938,0,20,4299,-5.233380,NaN,NaN

In [3]:
header_mentions = ['GlobalEventID',
'EventTimeDate',
'MentionTimeDate',
'MentionType',
'MentionSourceName',
'MentionIdentifier',
'SentenceID',
'Actor1CharOffset',
'Actor2CharOffset',
'ActionCharOffset',
'InRawText',
'Confidence',
'MentionDocLen',
'MentionDocTone',
'MentionDocTranslationInfo',
'Extras']

mentions.columns = header_mentions
mentions

,GlobalEventID,EventTimeDate,MentionTimeDate,MentionType,MentionSourceName,MentionIdentifier,SentenceID,Actor1CharOffset,Actor2CharOffset,ActionCharOffset,InRawText,Confidence,MentionDocLen,MentionDocTone,MentionDocTranslationInfo,Extras
0,1052903286,20220707000000,20220707000000,1,rbc.ru,https://www.rbc.ru/politics/06/07/2022/62c5b6a...,9,-1,3050,2993,1,100,9532,-0.827498,srclc:rus;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
1,993717919,20210707001500,20220707000000,1,aif.ru,https://aif.ru/society/history/zapal_dyatlova_...,36,-1,11287,11230,1,100,13603,-4.170364,srclc:rus;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
2,1052903287,20220707000000,20220707000000,1,digi24.ro,https://www.digi24.ro/stiri/externe/mai-multi-...,7,-1,1727,1711,1,100,2066,-1.294498,srclc:ron;eng:GT-RON 1.0,NaN
3,1052903288,20220707000000,20220707000000,1,euronews.com,http://arabic.euronews.com/2022/07/06/rome-rec...,6,826,861,851,0,10,1517,-5.309735,srclc:ara;eng:GT-ARA 1.0,NaN
4,1052903289,20220707000000,20220707000000,1,euronews.com,http://arabic.euronews.com/2022/07/06/rome-rec...,6,826,879,851,0,20,1517,-5.309735,srclc:ara;eng:GT-ARA 1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744,1052903941,20220707000000,20220707000000,1,es.vietnamplus.vn,https://es.vietnamplus.vn/agilizan-nexos-entre...,6,1125,1167,1155,0,40,1732,3.409091,srclc:spa;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
745,1052903942,20220707000000,20220707000000,1,es.vietnamplus.vn,https://es.vietnamplus.vn/presidente-de-vietna...,1,17,40,28,1,80,1830,2.508961,srclc:spa;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
746,1052903943,20220707000000,20220707000000,1,es.vietnamplus.vn,https://es.vietnamplus.vn/agilizan-nexos-entre...,6,1125,1182,1179,0,20,1732,3.409091,srclc:spa;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
747,1052903944,20220707000000,20220707000000,1,es.vietnamplus.vn,https://es.vietnamplus.vn/agilizan-nexos-entre...,1,92,181,137,0,40,1732,3.409091,srclc:spa;eng:Moses 2.1.1 / MosesCore Europarl...,NaN
748,1052903945,20220707000000,20220707000000,1,es.vietnamplus.vn,https://es.vietnamplus.vn/agilizan-nexos-entre...,1,92,143,103,1,60,1732,3.409091,srclc:spa;eng:Moses 2.1.1 / MosesCore Europarl...,NaN

In [22]:
mentions = pd.read_csv("../../data/raw/20220707000000.mentions.csv", delimiter="\t", header=None, names=header_mentions, usecols=['ActionGeo_CountryCode']).squeeze()
mentions

ValueError: Usecols do not match columns, columns expected but not found: ['ActionGeo_CountryCode']

In [13]:
def check_language(start, end):
    for date in pd.date_range(start, end, freq='15T').to_pydatetime():
        str_date = date.strftime("%Y%m%d%H%M%S")
        mentions = pd.read_csv(f"../../data/raw/{str_date}.mentions.csv", delimiter="\t", header=None, names=header_mentions, usecols=['MentionDocTranslationInfo']).squeeze()
        not_na_count = mentions.notna().sum()
        # print(not_na_count)
        if not_na_count > 0:
            print(f"Pas d'anglais à cette date: {date}")

In [14]:
start = dt(2023, 1, 7)
end = dt(2023, 1, 8)
check_language(start, end)

In [21]:
gkg = pd.read_csv("../../data/raw/20230107003000.translation.gkg.csv", delimiter="\t", header=None, encoding = "ISO-8859-1", usecols=[25])
gkg

                                                    25
0    srclc:fra;eng:Moses 2.1.1 / MosesCore Europarl...
1    srclc:fra;eng:Moses 2.1.1 / MosesCore Europarl...
2    srclc:fra;eng:Moses 2.1.1 / MosesCore Europarl...
3    srclc:fra;eng:Moses 2.1.1 / MosesCore Europarl...
4    srclc:fra;eng:Moses 2.1.1 / MosesCore Europarl...
..                                                 ...
960                           srclc:vie;eng:GT-VIE 1.0
961                           srclc:vie;eng:GT-VIE 1.0
962                           srclc:vie;eng:GT-VIE 1.0
963                           srclc:vie;eng:GT-VIE 1.0
964                           srclc:slv;eng:GT-SLV 1.0

[965 rows x 1 columns]

a) afficher le nombre d’articles/évènements qu’il y a eu pour chaque triplet (jour, pays de l’évènement, langue de l’article).

jour : Events[ Day, YearMonth, Year, DateAdd ] \
pays : Events[ (GeoEvents) ] (the Geo_FeatureID column should be used) \
langue : Mentions[ MentionDocTranslationInfo ]

lien event -> mention: GlobalEventID \
lien mention -> gkg: mentionIdentifier -> DocumentIdentifier

Localisation:
- Origine de l'actor
- Lieu de l'actor au moment de l'évenement
- Lieu de déroulement de l'action

Un acteur a donc un lieu d'origine fixe mais aussi un lieu associé à chaque évenement le concernant. Comment materialiser cela dans le graphe ? 
1) Noeud Lieu pour les origines des actors et les évenements + caractérisation du lieu dans le lien acteur évenement\
La redondance d'un noeud géographique et de propriété géographique dans des liens n'est elle pas dégueulasse ?
2) Pas de noeud lieu -> caractéristiques transferer dans les noeuds d'origines (origine devient une propriété d'actor ou event)

D'après les questions, il est préferable de garder un noeud lieu, la localisation des actors n'est pas très utiles pour y répondre

### Person

Besoin de differencier les acteurs à un niveau plus fin -> q3 (filtrer les personnes qui ...) \
Comment représenter ça dans Neo4j ? Heritage possible ? -> un noeud actor, comportant les propriété principales, associé à un noeud person ou organization etc