In [1]:
import pandas as pd
import zipfile
import shutil
import wget

In [2]:
df = pd.read_csv('http://data.gdeltproject.org/gdeltv2/masterfilelist.txt', delimiter=' ', header=None)

/var/folders/h9/3f0fc1qs2t3943x127_ynxmc0000gn/T/ipykernel_68297/1156648321.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('http://data.gdeltproject.org/gdeltv2/masterfilelist.txt', delimiter=' ', header=None)

In [3]:
df_multil = pd.read_csv('http://data.gdeltproject.org/gdeltv2/masterfilelist-translation.txt', delimiter=' ', header=None)

/var/folders/h9/3f0fc1qs2t3943x127_ynxmc0000gn/T/ipykernel_68297/3569745926.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_multil = pd.read_csv('http://data.gdeltproject.org/gdeltv2/masterfilelist-translation.txt', delimiter=' ', header=None)

In [6]:
extr_dir = '/Users/dorianfitton/Documents/Cours_Télécom/NoSQL_project_GDELT/explo/dorian/data'

In [6]:
df

,0,1,2
0,150383,297a16b493de7cf6ca809a7cc31d0b93,http://data.gdeltproject.org/gdeltv2/201502182...
1,318084,bb27f78ba45f69a17ea6ed7755e9f8ff,http://data.gdeltproject.org/gdeltv2/201502182...
2,10768507,ea8dde0beb0ba98810a92db068c0ce99,http://data.gdeltproject.org/gdeltv2/201502182...
3,149211,2a91041d7e72b0fc6a629e2ff867b240,http://data.gdeltproject.org/gdeltv2/201502182...
4,339037,dec3f427076b716a8112b9086c342523,http://data.gdeltproject.org/gdeltv2/201502182...
...,...,...,...
814765,76921,de39e45053d672c57797a840560a448a,http://data.gdeltproject.org/gdeltv2/202301131...
814766,4546104,1eb4972bca285c939c2ae281c009d1c8,http://data.gdeltproject.org/gdeltv2/202301131...
814767,71916,162d09f25a2a358865b0e20ad1b0952a,http://data.gdeltproject.org/gdeltv2/202301131...
814768,99075,1ca636e8d6e47f2394a974d6652a56b3,http://data.gdeltproject.org/gdeltv2/202301131...
814769,4271810,07510cd8f90bdb7a94267976c7a95774,http://data.gdeltproject.org/gdeltv2/202301131...

In [7]:
data = wget.download(df[2][0])
shutil.unpack_archive(data, extr_dir)

In [11]:
with zipfile.ZipFile(data,"r") as zip_ref:
    zip_ref.extractall(extr_dir)

In [2]:
sample = pd.read_csv('/Users/dorianfitton/Documents/Cours_Télécom/NoSQL_project_GDELT/explo/dorian/data/20150218230000.export.CSV', delimiter="\t", )

FileNotFoundError: [Errno 2] No such file or directory: '/Users/dorianfitton/Documents/Cours_Télécom/NoSQL_project_GDELT/explo/dorian/data/20150218230000.export.CSV'

In [14]:
sample

,410412347,20140218,201402,2014,2014.1315,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,4.1,"Waterkloof, Free State, South Africa.1",SF.1,SF03.1,77359.1,-30.3098.1,25.2971.1,-1299321.1,20150218230000,http://www.dailymaverick.co.za/article/2015-02-19-sona2015-jamming-state-security-agency-steps-forward-blames-low-ranking-operator/
0,410412348,20140218,201402,2014,2014.1315,NaN,NaN,NaN,NaN,NaN,...,4,"Bengaluru, Karnataka, India",IN,IN19,70159,12.9833,77.5833,-2090174,20150218230000,http://timesofindia.indiatimes.com/city/bengal...
1,410412349,20140218,201402,2014,2014.1315,NaN,NaN,NaN,NaN,NaN,...,4,"Great Southern, Victoria, Australia",AS,AS07,5387,-36.0667,146.4830,-1576477,20150218230000,http://www.voxy.co.nz/entertainment/coast-new-...
2,410412350,20140218,201402,2014,2014.1315,NaN,NaN,NaN,NaN,NaN,...,1,New Zealand,NZ,NZ,NaN,-41.0000,174.0000,NZ,20150218230000,http://www.voxy.co.nz/entertainment/coast-new-...
3,410412351,20140218,201402,2014,2014.1315,NaN,NaN,NaN,NaN,NaN,...,2,"Idaho, United States",US,USID,NaN,44.2394,-114.5100,ID,20150218230000,http://www.eastidahonews.com/2015/02/neil-patr...
4,410412352,20140218,201402,2014,2014.1315,AUS,AUSTRALIA,AUS,NaN,NaN,...,4,"Brisbane, Queensland, Australia",AS,AS04,154654,-27.5000,153.0170,-1561728,20150218230000,http://www.businessspectator.com.au/article/20...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2265,410414613,20150218,201502,2015,2015.1315,ran,RANA,NaN,NaN,ran,...,4,"Islamabad, Islamabad, Pakistan",PK,PK08,23674,33.7000,73.1667,-2762812,20150218230000,http://www.dailytimes.com.pk/national/19-Feb-2...
2266,410414614,20150218,201502,2015,2015.1315,ran,RANA,NaN,NaN,ran,...,4,"Agha Muhammad, Balochistan, Pakistan",PK,PK02,3606,30.5699,66.5961,356668,20150218230000,http://www.dailytimes.com.pk/national/19-Feb-2...
2267,410414615,20150218,201502,2015,2015.1315,ran,RANA,NaN,NaN,ran,...,4,"Islamabad, Islamabad, Pakistan",PK,PK08,23674,33.7000,73.1667,-2762812,20150218230000,http://www.dailytimes.com.pk/national/19-Feb-2...
2268,410414616,20150218,201502,2015,2015.1315,ran,RANA,NaN,NaN,ran,...,4,"Agha Muhammad, Balochistan, Pakistan",PK,PK02,3606,30.5699,66.5961,356668,20150218230000,http://www.dailytimes.com.pk/national/19-Feb-2...
2269,410414617,20150218,201502,2015,2015.1315,tib,TIBETAN,NaN,NaN,tib,...,4,"Amdo, Xizang, China",CH,CH14,13213,32.3333,91.6667,-1920650,20150218230000,http://www.bbg.gov/blog/2015/02/18/rfas-tibeta...

In [13]:
list_header= ['GlobalEventID','Day',	'MonthYear',	'Year',	'FractionDate',	'Actor1Code',	'Actor1Name',	'Actor1CountryCode',	'Actor1KnownGroupCode',	'Actor1EthnicCode',	'Actor1Religion1Code',	'Actor1Religion2Code',	'Actor1Type1Code',	'Actor1Type2Code',	'Actor1Type3Code',	'Actor2Code',	'Actor2Name',	'Actor2CountryCode',	'Actor2KnownGroupCode',	'Actor2EthnicCode',	'Actor2Religion1Code',	'Actor2Religion2Code',	'Actor2Type1Code',	'Actor2Type2Code',	'Actor2Type3Code',	'IsRootEvent',	'EventCode',	'EventBaseCode',	'EventRootCode',	'QuadClass',	'GoldsteinScale',	'NumMentions',	'NumSources',	'NumArticles',	'AvgTone',	'Actor1Geo_Type',	'Actor1Geo_FullName',	'Actor1Geo_CountryCode',	'Actor1Geo_ADM1Code',	'Actor1Geo_ADM2Code',	'Actor1Geo_Lat',	'Actor1Geo_Long',	'Actor1Geo_FeatureID',	'Actor2Geo_Type',	'Actor2Geo_FullName',	'Actor2Geo_CountryCode',	'Actor2Geo_ADM1Code',	'Actor2Geo_ADM2Code',	'Actor2Geo_Lat',	'Actor2Geo_Long',	'Actor2Geo_FeatureID',	'ActionGeo_Type',	'ActionGeo_FullName',	'ActionGeo_CountryCode',	'ActionGeo_ADM1Code',	'ActionGeo_ADM2Code',	'ActionGeo_Lat',	'ActionGeo_Long',	'ActionGeo_FeatureID',	'DATEADDED',	'SOURCEURL']

In [17]:
sample = pd.read_csv('/Users/dorianfitton/Documents/Cours_Télécom/NoSQL_project_GDELT/explo/dorian/data/20150218230000.export.CSV', delimiter="\t", header=None)

In [18]:
sample.columns=list_header

In [19]:
sample

,BALEVENTID,SQLDATE,MonthYear,Year,FractionDate,Actor1Code,Actor1Name,Actor1CountryCode,Actor1KnownGroupCode,Actor1EthnicCode,...,ActionGeo_Type,ActionGeo_FullName,ActionGeo_CountryCode,ActionGeo_ADM1Code,ActionGeo_ADM2Code,ActionGeo_Lat,ActionGeo_Long,ActionGeo_FeatureID,DATEADDED,SOURCEURL
0,410412347,20140218,201402,2014,2014.1315,NaN,NaN,NaN,NaN,NaN,...,4,"Waterkloof, Free State, South Africa",SF,SF03,77359,-30.3098,25.2971,-1299321,20150218230000,http://www.dailymaverick.co.za/article/2015-02...
1,410412348,20140218,201402,2014,2014.1315,NaN,NaN,NaN,NaN,NaN,...,4,"Bengaluru, Karnataka, India",IN,IN19,70159,12.9833,77.5833,-2090174,20150218230000,http://timesofindia.indiatimes.com/city/bengal...
2,410412349,20140218,201402,2014,2014.1315,NaN,NaN,NaN,NaN,NaN,...,4,"Great Southern, Victoria, Australia",AS,AS07,5387,-36.0667,146.4830,-1576477,20150218230000,http://www.voxy.co.nz/entertainment/coast-new-...
3,410412350,20140218,201402,2014,2014.1315,NaN,NaN,NaN,NaN,NaN,...,1,New Zealand,NZ,NZ,NaN,-41.0000,174.0000,NZ,20150218230000,http://www.voxy.co.nz/entertainment/coast-new-...
4,410412351,20140218,201402,2014,2014.1315,NaN,NaN,NaN,NaN,NaN,...,2,"Idaho, United States",US,USID,NaN,44.2394,-114.5100,ID,20150218230000,http://www.eastidahonews.com/2015/02/neil-patr...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2266,410414613,20150218,201502,2015,2015.1315,ran,RANA,NaN,NaN,ran,...,4,"Islamabad, Islamabad, Pakistan",PK,PK08,23674,33.7000,73.1667,-2762812,20150218230000,http://www.dailytimes.com.pk/national/19-Feb-2...
2267,410414614,20150218,201502,2015,2015.1315,ran,RANA,NaN,NaN,ran,...,4,"Agha Muhammad, Balochistan, Pakistan",PK,PK02,3606,30.5699,66.5961,356668,20150218230000,http://www.dailytimes.com.pk/national/19-Feb-2...
2268,410414615,20150218,201502,2015,2015.1315,ran,RANA,NaN,NaN,ran,...,4,"Islamabad, Islamabad, Pakistan",PK,PK08,23674,33.7000,73.1667,-2762812,20150218230000,http://www.dailytimes.com.pk/national/19-Feb-2...
2269,410414616,20150218,201502,2015,2015.1315,ran,RANA,NaN,NaN,ran,...,4,"Agha Muhammad, Balochistan, Pakistan",PK,PK02,3606,30.5699,66.5961,356668,20150218230000,http://www.dailytimes.com.pk/national/19-Feb-2...
2270,410414617,20150218,201502,2015,2015.1315,tib,TIBETAN,NaN,NaN,tib,...,4,"Amdo, Xizang, China",CH,CH14,13213,32.3333,91.6667,-1920650,20150218230000,http://www.bbg.gov/blog/2015/02/18/rfas-tibeta...

In [ ]:
sample_multil = pd.read_csv('/Users/dorianfitton/Documents/Cours_Télécom/NoSQL_project_GDELT/explo/dorian/data/20150218230000.export.CSV', delimiter="\t", header=None)

In [6]:
df_mentions = pd.read_csv('/Users/dorianfitton/Documents/Cours_Télécom/NoSQL_project_GDELT/data/20150218230000.mentions.CSV', delimiter='\t', header=None)

In [12]:
header_mentions = ['GlobalEventID',
'EventTimeDate',
'MentionTimeDate',
'MentionType',
'MentionSourceName',
'MentionIdentifier',
'SentenceID',
'Actor1CharOffset',
'Actor2CharOffset',
'ActionCharOffset',
'InRawText',
'Confidence',
'MentionDocLen',
'MentionDocTone',
'MentionDocTranslationInfo',
'Extras']

In [9]:
df_mentions.columns=header_mentions

In [10]:
df_mentions

,LEVENTID,EventTimeDate,MentionTimeDate,MentionType,MentionSourceName,MentionIdentifier,SentenceID,Actor1CharOffset,Actor2CharOffset,ActionCharOffset,InRawText,Confidence,MentionDocLen,MentionDocTone,MentionDocTranslationInfo,Extras
0,410412347,20150218230000,20150218230000,1,dailymaverick.co.za,http://www.dailymaverick.co.za/article/2015-02...,19,-1,4594,4634,1,50,6665,-4.477612,NaN,NaN
1,410412348,20150218230000,20150218230000,1,indiatimes.com,http://timesofindia.indiatimes.com/city/bengal...,2,-1,300,344,1,50,2541,2.078522,NaN,NaN
2,410412349,20150218230000,20150218230000,1,voxy.co.nz,http://www.voxy.co.nz/entertainment/coast-new-...,4,-1,1297,1232,0,10,2576,7.517084,NaN,NaN
3,410412350,20150218230000,20150218230000,1,voxy.co.nz,http://www.voxy.co.nz/entertainment/coast-new-...,4,-1,1298,1233,1,20,2576,7.517084,NaN,NaN
4,410412351,20150218230000,20150218230000,1,eastidahonews.com,http://www.eastidahonews.com/2015/02/neil-patr...,1,-1,103,122,1,100,1432,0.000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8457,410414615,20150218230000,20150218230000,1,dailytimes.com.pk,http://www.dailytimes.com.pk/national/19-Feb-2...,3,396,424,442,0,20,1994,-3.703704,NaN,NaN
8458,410414616,20150218230000,20150218230000,1,dailytimes.com.pk,http://www.dailytimes.com.pk/national/19-Feb-2...,3,396,424,367,0,20,1994,-3.703704,NaN,NaN
8459,410232648,20150218100000,20150218230000,1,suttonguardian.co.uk,http://www.suttonguardian.co.uk/news/national/...,6,1870,-1,1803,1,100,5040,-0.738916,NaN,NaN
8460,410339294,20150218171500,20150218230000,1,edgeboston.com,http://www.edgeboston.com/entertainment/celebr...,2,454,-1,411,1,50,858,6.250000,NaN,NaN
8461,410414617,20150218230000,20150218230000,1,bbg.gov,http://www.bbg.gov/blog/2015/02/18/rfas-tibeta...,1,318,-1,345,1,100,1584,-0.411523,NaN,NaN

In [16]:
df_gkg = pd.read_csv('/Users/dorianfitton/Documents/Cours_Télécom/NoSQL_project_GDELT/data/raw/20190205231500.gkg.csv', delimiter='\t', usecols=header_gkg)

ValueError: Usecols do not match columns, columns expected but not found: ['GKGRecordID', 'SharingImage', 'DocumentIdentifier', 'SocialVideoEmbeds', 'DATE', 'Locations', 'RelatedImages', 'Quotations', 'V2Tone', 'SourceCommonName', 'TranslationInfo', 'Persons', 'AllNames', 'GCAM', 'V2Organizations', 'V2Counts', 'SocialImageEmbeds', 'Counts', 'Themes', 'V2Persons', 'Dates', 'Organizations', 'V2Locations', 'Amounts', 'Extras', 'V2Themes', 'SourceCollectionIdentifier']

In [12]:
df_gkg

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,20190205231500-0,20190205231500,1,streetwisereport.com,http://streetwisereport.com/danaher-corporatio...,NaN,NaN,ECON_STOCKMARKET;CRISISLEX_C07_SAFETY;TAX_FNCA...,"TAX_ECON_PRICE,868;TAX_ECON_PRICE,929;TAX_ECON...",NaN,...,"wc:221,c1.2:5,c1.3:1,c12.1:13,c12.10:25,c12.12...",NaN,NaN,NaN,NaN,NaN,"Danaher Corporation,72","42,attracting passive investors,875;746270,sha...",NaN,<PAGE_AUTHORS>Aaron Smithies</PAGE_AUTHORS>
1,20190205231500-1,20190205231500,1,cranstononline.com,http://cranstononline.com/stories/a-warm-welco...,NaN,NaN,NaN,NaN,"3#Boston, Massachusetts, United States#US#USMA...",...,"wc:504,c12.1:43,c12.10:29,c12.12:12,c12.13:7,c...",https://cdn2.creativecirclemedia.com/warwick/o...,NaN,NaN,https://youtube.com/user/warwickbeacon;,NaN,"State Police,60;Super Bowl,461;Super Bowl,1012...","12,who had staked out,514;6,Super Bowl rings,1...",NaN,NaN
2,20190205231500-2,20190205231500,1,montanakaimin.com,http://www.montanakaimin.com/arts_and_culture/...,NaN,NaN,TAX_FNCACT;TAX_FNCACT_CHOREOGRAPHER;TAX_FNCACT...,"AGRICULTURE,650;TAX_FNCACT_FARMER,650;TAX_FNCA...","2#New York, United States#US#USNY#42.1497#-74....",...,"wc:132,c12.1:11,c12.10:20,c12.12:3,c12.13:8,c1...",https://bloximages.newyork1.vip.townnews.com/m...,NaN,NaN,https://youtube.com/channel/UCslhVPsVAO7YkdzOf...,NaN,"Top Hat,87;Sexy Chocolate Show,420;Heather Ada...","10,dollars adv,279;13,dollars adv,848;16,dolla...",NaN,<PAGE_AUTHORS>Montana Kaimin</PAGE_AUTHORS><PA...
3,20190205231500-3,20190205231500,1,richmond-news.com,https://www.richmond-news.com/peladeau-may-be-...,NaN,NaN,WB_678_DIGITAL_GOVERNMENT;WB_694_BROADCAST_AND...,"WB_1104_MACROECONOMIC_VULNERABILITY_AND_DEBT,1...","4#Montreal, Quebec, Canada#CA#CA10#45.5#-73.58...",...,"wc:168,c1.2:2,c1.3:1,c12.1:7,c12.10:15,c12.12:...",https://images.glaciermedia.ca/polopoly_fs/1.2...,NaN,NaN,NaN,NaN,"Teo Taxi,165;Karl Peladeau,252;Teo Tax,636;Teo...","400,drivers have been unemployed,491;25000000,...",NaN,<PAGE_PRECISEPUBTIMESTAMP>20190205105900</PAGE...
4,20190205231500-4,20190205231500,1,wusa9.com,https://www.wusa9.com/article/news/nation-worl...,NaN,NaN,KILL;CRISISLEX_T03_DEAD;ARREST;SOC_GENERALCRIM...,"EDUCATION,816;EDUCATION,874;MANMADE_DISASTER_I...","3#Miami, Florida, United States#US#USFL#25.774...",...,"wc:172,c12.1:6,c12.10:13,c12.12:6,c12.13:6,c12...",https://www.wusa9.com/img/resize/media.wtsp.co...,NaN,NaN,https://youtube.com/iframe_api?noext;,NaN,"Trayvon Martin,15;George Zimmerman,135;Preside...","17,when he was shot,51;2000000,times,880;",NaN,<PAGE_LINKS>https://www.wtsp.com/article/news/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3003,20190205231500-57,20190205231500,1,whdg.com,http://www.whdg.com/news/bebe-rexhas-hoping-to...,NaN,NaN,USPEC_POLITICS_GENERAL1;TAX_FNCACT;TAX_FNCACT_...,"EPU_CATS_REGULATION,760;TAX_FNCACT_ARTIST,581;...","2#Florida, United States#US#USFL#27.8333#-81.7...",...,"wc:128,c1.1:1,c12.1:12,c12.10:7,c12.12:1,c12.1...",NaN,NaN,NaN,https://youtube.com/embed/zDo0H8Fm7d0;https://...,"446|89||We've spoken on text , but hopefully w...","Recording AcademyAfter,39;Florida Georgia Line...",NaN,NaN,<PAGE_LINKS>http://www.people.com/</PAGE_LINKS>
3004,20190205231500-58,20190205231500,1,wearegreenbay.com,https://www.wearegreenbay.com/news/local-news/...,NaN,NaN,NATURAL_DISASTER;NATURAL_DISASTER_WINTER_STORM...,"NATURAL_DISASTER_WINTRY,806;NATURAL_DISASTER_W...","3#Oconto, Wisconsin, United States#US#USWI#44....",...,"wc:259,c12.1:13,c12.10:29,c12.12:11,c12.13:13,...",https://media.wearegreenbay.com/nxsglobal/wear...,NaN,NaN,https://youtube.com/channel/UCvRw8OyWw09DA1ndw...,NaN,"Snow Arrives Tonight,21;Larger System Possible...","5,for the latest winter,1240;5,mobile app,1295;",NaN,<PAGE_AUTHORS>Chad Roethlisberger</PAGE_AUTHOR...
3005,20190205231500-59,20190205231500,1,wickedlocal.com,https://stoneham.wickedlocal.com/news/20190205...,NaN,NaN,LEADER;TAX_FNCACT;TAX_FNCACT_LAWMAKERS;USPEC_P...,"GENERAL_GOVERNMENT,2704;EPU_POLICY_GOVERNMENT,...","3#Boston, Massachusetts, United States#US#USMA...",...,"wc:450,c1.2:4,c12.1:33,c12.10:35,c12.12:10,c12...",https://stoneham.wickedlocal.com/storyimage/WL...,NaN,NaN,NaN,1722|25||strong local media market,"Massachusetts Municipal,170;Lori Ehrlich,430;M...","555,markets,1742;37,states,1753;9,dailies,1768...",NaN,<PAGE_AUTHORS>Katie Lannanswampscott@wickedloc...
3006,20190205231500-60,20190205231500,1,foxrochester.com,https://foxrochester.com/news/nation-world/wat...,NaN,NaN,TAX_FNCACT;TAX_FNCACT_SPEAKER;DEMOCRACY;TAX_FN...,"TAX_FNCACT_SPEAKER,45;TAX_FNCACT_WOMEN,92;TAX_...","3#Washington, Washington, United States#US#USD...",...,"wc:46,c12.1:1,c12.10:4,c12.12:1,c12.14:3,c12.3...",http://static-20.sinclairstoryline.com/resourc...,NaN,NaN,NaN,NaN,"Speaker Nancy Pelosi,39;Democratic Women,75;Wo...",NaN,NaN,<PAGE_AUTHORS>Sinclair Broadcast Group</PAGE_A...
3007,20190205231500-61,20190205231500,1,joker.com,https://joker.com/?mode=order&do_next=landingp...,NaN,NaN,EPU_ECONOMY_HISTORIC;TAX_FNCACT;TAX_FNCACT_REG...,"TAX_FNCACT_REGISTRAR,66;EPU_ECONOMY_HISTORIC,4...",NaN,...,"wc:36,c12.1:6,c12.10:1,c12.14:1,c12.3:3,c12.4:...",NaN,NaN,NaN,NaN,NaN,"About Joker,13",NaN,NaN,NaN

In [13]:
header_gkg = ['GKGRecordID','DATE','SourceCollectionIdentifier','SourceCommonName','DocumentIdentifier','Counts','V2Counts','Themes','V2Themes','Locations','V2Locations','Persons','V2Persons','Organizations','V2Organizations','V2Tone','Dates','GCAM','SharingImage','RelatedImages','SocialImageEmbeds','SocialVideoEmbeds','Quotations','AllNames','Amounts','TranslationInfo','Extras']

In [14]:
df_gkg.columns = header_gkg

In [ ]:
df_gkg.to_string()

In [15]:
pd.reset_option('all')
df_gkg

/Users/dorianfitton/opt/anaconda3/envs/bgd/lib/python3.10/site-packages/pandas/_config/config.py:653: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead.
  warnings.warn(d.msg, FutureWarning)
/Users/dorianfitton/opt/anaconda3/envs/bgd/lib/python3.10/site-packages/pandas/_config/config.py:653: FutureWarning:
: boolean
    use_inf_as_null had been deprecated and will be removed in a future
    version. Use `use_inf_as_na` instead.

  warnings.warn(d.msg, FutureWarning)

,GKGRecordID,DATE,SourceCollectionIdentifier,SourceCommonName,DocumentIdentifier,Counts,V2Counts,Themes,V2Themes,Locations,...,GCAM,SharingImage,RelatedImages,SocialImageEmbeds,SocialVideoEmbeds,Quotations,AllNames,Amounts,TranslationInfo,Extras
0,20190205231500-0,20190205231500,1,streetwisereport.com,http://streetwisereport.com/danaher-corporatio...,NaN,NaN,ECON_STOCKMARKET;CRISISLEX_C07_SAFETY;TAX_FNCA...,"TAX_ECON_PRICE,868;TAX_ECON_PRICE,929;TAX_ECON...",NaN,...,"wc:221,c1.2:5,c1.3:1,c12.1:13,c12.10:25,c12.12...",NaN,NaN,NaN,NaN,NaN,"Danaher Corporation,72","42,attracting passive investors,875;746270,sha...",NaN,<PAGE_AUTHORS>Aaron Smithies</PAGE_AUTHORS>
1,20190205231500-1,20190205231500,1,cranstononline.com,http://cranstononline.com/stories/a-warm-welco...,NaN,NaN,NaN,NaN,"3#Boston, Massachusetts, United States#US#USMA...",...,"wc:504,c12.1:43,c12.10:29,c12.12:12,c12.13:7,c...",https://cdn2.creativecirclemedia.com/warwick/o...,NaN,NaN,https://youtube.com/user/warwickbeacon;,NaN,"State Police,60;Super Bowl,461;Super Bowl,1012...","12,who had staked out,514;6,Super Bowl rings,1...",NaN,NaN
2,20190205231500-2,20190205231500,1,montanakaimin.com,http://www.montanakaimin.com/arts_and_culture/...,NaN,NaN,TAX_FNCACT;TAX_FNCACT_CHOREOGRAPHER;TAX_FNCACT...,"AGRICULTURE,650;TAX_FNCACT_FARMER,650;TAX_FNCA...","2#New York, United States#US#USNY#42.1497#-74....",...,"wc:132,c12.1:11,c12.10:20,c12.12:3,c12.13:8,c1...",https://bloximages.newyork1.vip.townnews.com/m...,NaN,NaN,https://youtube.com/channel/UCslhVPsVAO7YkdzOf...,NaN,"Top Hat,87;Sexy Chocolate Show,420;Heather Ada...","10,dollars adv,279;13,dollars adv,848;16,dolla...",NaN,<PAGE_AUTHORS>Montana Kaimin</PAGE_AUTHORS><PA...
3,20190205231500-3,20190205231500,1,richmond-news.com,https://www.richmond-news.com/peladeau-may-be-...,NaN,NaN,WB_678_DIGITAL_GOVERNMENT;WB_694_BROADCAST_AND...,"WB_1104_MACROECONOMIC_VULNERABILITY_AND_DEBT,1...","4#Montreal, Quebec, Canada#CA#CA10#45.5#-73.58...",...,"wc:168,c1.2:2,c1.3:1,c12.1:7,c12.10:15,c12.12:...",https://images.glaciermedia.ca/polopoly_fs/1.2...,NaN,NaN,NaN,NaN,"Teo Taxi,165;Karl Peladeau,252;Teo Tax,636;Teo...","400,drivers have been unemployed,491;25000000,...",NaN,<PAGE_PRECISEPUBTIMESTAMP>20190205105900</PAGE...
4,20190205231500-4,20190205231500,1,wusa9.com,https://www.wusa9.com/article/news/nation-worl...,NaN,NaN,KILL;CRISISLEX_T03_DEAD;ARREST;SOC_GENERALCRIM...,"EDUCATION,816;EDUCATION,874;MANMADE_DISASTER_I...","3#Miami, Florida, United States#US#USFL#25.774...",...,"wc:172,c12.1:6,c12.10:13,c12.12:6,c12.13:6,c12...",https://www.wusa9.com/img/resize/media.wtsp.co...,NaN,NaN,https://youtube.com/iframe_api?noext;,NaN,"Trayvon Martin,15;George Zimmerman,135;Preside...","17,when he was shot,51;2000000,times,880;",NaN,<PAGE_LINKS>https://www.wtsp.com/article/news/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3003,20190205231500-57,20190205231500,1,whdg.com,http://www.whdg.com/news/bebe-rexhas-hoping-to...,NaN,NaN,USPEC_POLITICS_GENERAL1;TAX_FNCACT;TAX_FNCACT_...,"EPU_CATS_REGULATION,760;TAX_FNCACT_ARTIST,581;...","2#Florida, United States#US#USFL#27.8333#-81.7...",...,"wc:128,c1.1:1,c12.1:12,c12.10:7,c12.12:1,c12.1...",NaN,NaN,NaN,https://youtube.com/embed/zDo0H8Fm7d0;https://...,"446|89||We've spoken on text , but hopefully w...","Recording AcademyAfter,39;Florida Georgia Line...",NaN,NaN,<PAGE_LINKS>http://www.people.com/</PAGE_LINKS>
3004,20190205231500-58,20190205231500,1,wearegreenbay.com,https://www.wearegreenbay.com/news/local-news/...,NaN,NaN,NATURAL_DISASTER;NATURAL_DISASTER_WINTER_STORM...,"NATURAL_DISASTER_WINTRY,806;NATURAL_DISASTER_W...","3#Oconto, Wisconsin, United States#US#USWI#44....",...,"wc:259,c12.1:13,c12.10:29,c12.12:11,c12.13:13,...",https://media.wearegreenbay.com/nxsglobal/wear...,NaN,NaN,https://youtube.com/channel/UCvRw8OyWw09DA1ndw...,NaN,"Snow Arrives Tonight,21;Larger System Possible...","5,for the latest winter,1240;5,mobile app,1295;",NaN,<PAGE_AUTHORS>Chad Roethlisberger</PAGE_AUTHOR...
3005,20190205231500-59,20190205231500,1,wickedlocal.com,https://stoneham.wickedlocal.com/news/20190205...,NaN,NaN,LEADER;TAX_FNCACT;TAX_FNCACT_LAWMAKERS;USPEC_P...,"GENERAL_GOVERNMENT,2704;EPU_POLICY_GOVERNMENT,...","3#Boston, Massachusetts, United States#US#USMA...",...,"wc:450,c1.2:4,c12.1:33,c12.10:35,c12.12:10,c12...",https://stoneham.wickedlocal.com/storyimage/WL...,NaN,NaN,NaN,1722|25||strong local media market,"Massachusetts Municipal,170;Lori Ehrlich,430;M...","555,markets,1742;37,states,1753;9,dailies,1768...",NaN,<PAGE_AUTHORS>Katie Lannanswampscott@wickedloc...
3006,20190205231500-60,20190205231500,1,foxrochester.com,https://foxrochester.com/news/nation-world/wat...,NaN,NaN,TAX_FNCACT;TAX_FNCACT_SPEAKER;DEMOCRACY;TAX_FN...,"TAX_FNCACT_SPEAKER,45;TAX_FNCACT_WOMEN,92;TAX_...","3#Washington, Washington, United States#US#USD...",...,"wc:46,c12.1:1,c12.10:4,c12.12:1,c12.14:3,c12.3...",http://static-20.sinclairstoryline.com/resourc...,NaN,NaN,NaN,NaN,"Speaker Nancy Pelosi,39;Democratic Women,75;Wo...",NaN,NaN,<PAGE_AUTHORS>Sinclair Broadcast Group</PAGE_A...
3007,20190205231500-61,20190205231500,1,joker.com,https://joker.com/?mode=order&do_next=landingp...,NaN,NaN,EPU_ECONOMY_HISTORIC;TAX_FNCACT;TAX_FNCACT_REG...,"TAX_FNCACT_REGISTRAR,66;EPU_ECONOMY_HISTORIC,4...",NaN,...,"wc:36,c12.1:6,c12.10:1,c12.14:1,c12.3:3,c12.4:...",NaN,NaN,NaN,NaN,NaN,"About Joker,13",NaN,NaN,NaN

In [10]:
df_gkg.to_csv("/Users/dorianfitton/Documents/Cours_Télécom/NoSQL_project_GDELT/data/df_gkg_with_headers.csv")

In [17]:
dir_data = '/Users/dorianfitton/Documents/Cours_Télécom/NoSQL_project_GDELT/data'
type='gkg'
df_gkg.to_csv(dir_data+f'/df_{type}_with_headers_test.csv')

In [ ]:
4#Wellington, New Zealand (General), New Zealand#NZ#NZ00#-41.3#174.783#-1521348;1#New Zealand#NZ#NZ#-41#174#NZ;1#Malaysia#NZ#MY#2.5#112.5#MY;4#Brooklyn, New Zealand (General), New Zealand#NZ#NZ00#...