In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('http://data.gdeltproject.org/gdeltv2/masterfilelist.txt', delimiter=' ', header=None)
df

/var/folders/7b/ktwl248x3bs5nty14smdbq8h0000gn/T/ipykernel_3200/1706048213.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('http://data.gdeltproject.org/gdeltv2/masterfilelist.txt', delimiter=' ', header=None)

,0,1,2
0,150383,297a16b493de7cf6ca809a7cc31d0b93,http://data.gdeltproject.org/gdeltv2/201502182...
1,318084,bb27f78ba45f69a17ea6ed7755e9f8ff,http://data.gdeltproject.org/gdeltv2/201502182...
2,10768507,ea8dde0beb0ba98810a92db068c0ce99,http://data.gdeltproject.org/gdeltv2/201502182...
3,149211,2a91041d7e72b0fc6a629e2ff867b240,http://data.gdeltproject.org/gdeltv2/201502182...
4,339037,dec3f427076b716a8112b9086c342523,http://data.gdeltproject.org/gdeltv2/201502182...
...,...,...,...
820258,111391,3f8c49cc11988c4412825c0d17626866,http://data.gdeltproject.org/gdeltv2/202302011...
820259,5666636,78767be23c8efcbaa5bf0afef2684e6a,http://data.gdeltproject.org/gdeltv2/202302011...
820260,79455,3b9cb674ef13ed59eeb703bf98651f71,http://data.gdeltproject.org/gdeltv2/202302011...
820261,106153,4f4f7d973fae6f886919b49f3e615373,http://data.gdeltproject.org/gdeltv2/202302011...
820262,5837682,a15cffab3423e93c434e97111874adf9,http://data.gdeltproject.org/gdeltv2/202302011...

In [12]:
df = pd.read_csv("/Users/guillaumescotto/TélécomParis/Data/20230112.export.CSV",delimiter ='\t',header=None,low_memory=False)

In [13]:
df

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,57
0,1079765918,20220112,202201,2022,2022.0329,NaN,NaN,NaN,NaN,NaN,...,758474,3,"Cedar County, Missouri, United States",US,USMO,37.7334,-93.8669,758474,20230112,https://www.stltoday.com/news/state-and-region...
1,1079765919,20220112,202201,2022,2022.0329,NaN,NaN,NaN,NaN,NaN,...,423587,3,"Houston, Texas, United States",US,USTX,29.7633,-95.3633,1380948,20230112,https://herald-review.com/news/state-and-regio...
2,1079765920,20220112,202201,2022,2022.0329,NaN,NaN,NaN,NaN,NaN,...,758474,3,"Cedar County, Missouri, United States",US,USMO,37.7334,-93.8669,758474,20230112,https://www.stltoday.com/news/state-and-region...
3,1079765921,20220112,202201,2022,2022.0329,JUD,JUDGE,NaN,NaN,NaN,...,351615,3,"Atlanta, Georgia, United States",US,USGA,33.7490,-84.3880,351615,20230112,https://www.chronicleonline.com/news/national/...
4,1079765922,20220112,202201,2022,2022.0329,JUD,JUDGE,NaN,NaN,NaN,...,GA,2,"Georgia, United States",US,USGA,32.9866,-83.6487,GA,20230112,https://www.chronicleonline.com/news/national/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114883,1079939272,20230112,202301,2023,2023.0329,cad,CADDO,NaN,NaN,cad,...,1348410,3,"Texas Department Of Public Safety, Texas, Unit...",US,USTX,30.3263,-97.7242,1348410,20230112,https://www.ktbs.com/news/cpso-other-agencies-...
114884,1079939273,20230112,202301,2023,2023.0329,cad,CADDO,NaN,NaN,cad,...,1369752,3,"Texarkana, Texas, United States",US,USTX,33.4251,-94.0477,1369752,20230112,https://www.ktbs.com/news/cpso-other-agencies-...
114885,1079939274,20230112,202301,2023,2023.0329,fan,FANG,NaN,NaN,fan,...,10529074,4,"Luyang, Shaanxi, China",CH,CH26,34.7550,109.8330,10529074,20230112,https://www.thestar.com.my/news/nation/2023/01...
114886,1079939275,20230112,202301,2023,2023.0329,fan,FANG,NaN,NaN,fan,...,10529074,4,"Luyang, Shaanxi, China",CH,CH26,34.7550,109.8330,10529074,20230112,https://www.thestar.com.my/news/nation/2023/01...
114887,1079939276,20230112,202301,2023,2023.0329,moh,MOHAWK,NaN,NaN,moh,...,-571850,4,"Quebec, Quebec, Canada",CA,CA10,47.5000,-72.0000,-571850,20230112,https://www.timescolonist.com/national-news/of...

In [4]:
df = pd.read_csv("/Users/guillaumescotto/TélécomParis/NoSQL_project_GDELT/data/samples/20150218230000.gkg.CSV",delimiter ='\t',header=None,low_memory=False)

In [5]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,20150218230000-0,20150218230000,2,BBC Monitoring,as listed in Russian /BBC Monitoring/(c) BBC,"ARREST#400#political#4#Rossiya, Orenburgskaya ...","ARREST#400#political#4#Rossiya, Orenburgskaya ...",TERROR;REBELS;TAX_ETHNICITY;TAX_ETHNICITY_UKRA...,"TAX_FNCACT,2011;TAX_FNCACT,3449;TAX_FNCACT,381...","4#Budapest, Budapest, Hungary#RS#HU05#47.5#19....",...,"wc:693,c1.1:1,c1.2:1,c12.1:43,c12.10:58,c12.11...",NaN,NaN,NaN,NaN,1332|134||prisoners are treated humanely ; the...,"Channel One,628;Channel One,755;Channel One,14...","3,channels,476;3,channels reported,824;1,corre...",NaN,NaN
1,20150218230000-1,20150218230000,2,BBC Monitoring,"Al-Sharq al-Awsat website, London/BBC Monitori...",NaN,NaN,TAX_FNCACT;TAX_FNCACT_ENVOY;TAX_ETHNICITY;TAX_...,"IDEOLOGY,6790;IDEOLOGY,10592;KILL,1960;KILL,13...",1#Qatar#SA#QA#25.5#51.25#QA;1#Syria#SA#SY#35#3...,...,"wc:2376,c1.2:1,c1.4:7,c12.1:163,c12.10:276,c12...",NaN,NaN,NaN,NaN,332|26||greatly complicate matters#4494|37||ma...,"Emrullah Isler,83;Arab Spring,3571;Development...","2,fronts at the political,1455;2,main strategi...",NaN,NaN
2,20150218230000-2,20150218230000,1,wjon.com,http://wjon.com/wjon-news-on-demand-wednesday-...,NaN,NaN,MANMADE_DISASTER;MANMADE_DISASTER_WITHOUT_POWE...,"MANMADE_DISASTER,91;POWER_OUTAGE,91;",NaN,...,"wc:93,c12.1:7,c12.10:10,c12.12:5,c12.13:4,c12....",http://wac.450F.edgecastcdn.net/80450F/wjon.co...,http:/wac.450F.edgecastcdn.net/80450F/wjon.com...,NaN,https://youtube.com/channel/;https://youtube.c...,NaN,"Waite Park,125;City Food,233;Adobe Flash Playe...","500,people were without power,51;",NaN,NaN
3,20150218230000-3,20150218230000,1,wjol.com,http://www.wjol.com/common/more.php?m=15&r=3&i...,NaN,NaN,LEADER;TAX_FNCACT;TAX_FNCACT_GOVERNOR;TAX_POLI...,"TAX_FNCACT,131;TAX_POLITICAL_PARTY,664;TAX_FNC...","2#Wisconsin, United States#US#USWI#44.2563#-89...",...,"wc:103,c12.1:4,c12.10:13,c12.12:7,c12.13:6,c12...",NaN,NaN,NaN,NaN,NaN,"Governor Rauner,41;Speaker Michael Madigan,158...",NaN,NaN,NaN
4,20150218230000-4,20150218230000,1,straitstimes.com,http://www.straitstimes.com:80/news/world/unit...,NaN,NaN,DRONES;TAX_WORLDMAMMALS;TAX_WORLDMAMMALS_MICE;...,"TAX_FNCACT,634;TAX_FNCACT,1248;TAX_FNCACT,907;...","1#United States#US#US#38#-97#US;3#Miami, Flori...",...,"wc:255,c12.1:10,c12.10:28,c12.12:11,c12.13:7,c...",http://www.straitstimes.com/sites/straitstimes...,NaN,NaN,NaN,NaN,"United States,583;Columbia University Medical ...","5,weeks,1194;",NaN,NaN